// <auto-generated />
using System;
using IrisFlowerWeb.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrisFlowerWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IrisFlowerWeb.Models.IrisData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("FlowerType")
                        .HasColumnType("int");

                    b.Property<float>("PetalLength")
                        .HasColumnType("float");

                    b.Property<float>("PetalWidth")
                        .HasColumnType("float");

                    b.Property<float>("SepalLength")
                        .HasColumnType("float");

                    b.Property<float>("SepalWidth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("IrisDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
