// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IrisFlowerWeb.Migrations
{
    [DbContext(typeof(IrisFlowerContext))]
    partial class IrisFlowerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("IrisFlowerWeb.Models.IrisFlower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FlowerType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PetalLength")
                        .HasColumnType("REAL");

                    b.Property<float>("PetalWidth")
                        .HasColumnType("REAL");

                    b.Property<float>("SepalLength")
                        .HasColumnType("REAL");

                    b.Property<float>("SepalWidth")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("IrisFlower");
                });
#pragma warning restore 612, 618
        }
    }
}
